apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-conn-dest
  namespace: confluent
spec:
  name: clusterlink-destination-link
  sourceInitiatedLink:
    linkMode: Destination
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: confluent
  sourceKafkaCluster:
    kafkaRestClassRef:
      name: krc-cfk
      namespace: confluent
  mirrorTopics:
    - name: topic.from.destination
  configs:
    local.security.protocol: SASL_SSL