apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: cl-source-init
  namespace: confluent
spec:
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cfk
      namespace: confluent
  sourceKafkaCluster:
    tls:
      enabled: true
      secretRef: source-ccloud-cert
    bootstrapEndpoint: pkc-xxx.us-east-2.aws.confluent.cloud:9092
    clusterID: lkc-xxx
    authentication:
      type: plain
      jaasConfigPassThrough:
        secretRef: source-ccloud-jaas-credential
  mirrorTopics:
  - name: topic.from.source
