apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-dest-side
  namespace: confluent
spec:
  name: cl-destination-init
  sourceInitiatedLink:
    linkMode: Destination
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: confluent
  sourceKafkaCluster:
    kafkaRestClassRef:
      name: krc-cfk
      namespace: confluent
  mirrorTopics:
    - name: topic.from.source
#     sourceTopicName: mytopic
#  mirrorTopicOptions:
#    prefix: myprefix    
  configs:
    local.security.protocol: SASL_SSL