apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: krc-cloud
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: https://pkc-xxxx.us-east-2.azure.confluent.cloud:443
    kafkaClusterID: lkc-xxxx
    authentication:
      type: basic
      basic:
        secretRef: restclass-ccloud